SELECT
    MONTH(START_DATE) as MONTH,
    t1.CAR_ID,
    COUNT(HISTORY_ID) as RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY t1
JOIN
    (SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT (HISTORY_ID) >= 5
    ) t2
ON
    t1.CAR_ID = t2.CAR_ID
WHERE
    t1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH(START_DATE), CAR_ID
HAVING
    COUNT(HISTORY_ID) > 0
ORDER BY
    MONTH(START_DATE) ASC, CAR_ID DESC
