SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(PO.AMOUNT) * fp.PRICE
FROM
    FOOD_ORDER fo
JOIN
    FOOD_PRODUCT fp
ON
    fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE
    fo.PRODUCE_DATE between '2022-05-01' AND '2022-05-31'
GROUP BY
    PRODUCT_ID, PRODUCT_NAME