SELECT ANIMAL_ID,NAME FROM ANIMAL_OUTS WHERE ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID)

SELECT O.ANIMAL_ID,O.NAME FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID WHERE INTAKE_CONDITION IS NULL