SELECT
    a.AUTHOR_ID as AUTHOR_ID,
    a.AUTHOR_NAME as AUTHOR_NAME,
    b.CATEGORY as CATEGORY,
    SUM(bs.SALES * b.PRICE) as TOTAL_SALES
FROM
    AUTHOR a
        JOIN
    BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
        JOIN
    BOOK_SALES bs ON bs.BOOK_ID = b.BOOK_ID
WHERE
        bs.SALES_DATE >= "2022-01-01" AND bs.SALES_DATE < "2022-02-01"
GROUP BY
    a.AUTHOR_ID,b.CATEGORY
ORDER BY
    AUTHOR_ID ASC , CATEGORY DESC;